import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <script
        async
        defer
        crossorigin="anonymous"
        src="https://connect.facebook.net/en_US/all.js"
      ></script>
      <body className={inter.className}>
        <div className="fb-root">{children}</div>
      </body>
      <title>Facebook Helpdesk</title>
    </html>
  );
}
